### ISSUE TITLE
Whatup (this isnt an issue lol)

### ISSUE THREAD

**Issue by mknrls** [r3pwn/android_device_google_molly#1]
Hey whatup,

Im the one who create the https://github.com/adt1-dev repo, with the help of unjustified_dev.
Im seeing you are doing great progress and was wondering if you want me to add you to the repo to help the development grow. I create the organization repo to centralize and help the poor adt-1 development. 

Let me know if you are interested, btw im still a new newbie with and android development and have alot to learn. 

Mark Norelus (mknrls)

**Comment by r3pwn** [comment]
Yeah, sounds good to me!

**Comment by mknrls** [comment]
cool. added you

**Comment by npjohnson** [comment]
Could you add me as well? R3pwn, myself and one other are in a Development chat (pertaining to the ADT-1).

Thanks.

**Comment by abeatte** [comment]
Sure, you can add me. Thanks.

**Comment by mknrls** [comment]
@npjohnson @abeatte added :D

**Comment by halfluck** [comment]
So many kinds of Awesome!

**Comment by mknrls** [comment]
@halfluck happy to this device come alive again lol

**Comment by halfluck** [comment]
Yeah for sure, Mine is a daily driver I easily use it 4-5 hours a day, The features that the have been added to the Nexus Player CM12.1 branch are nothing short of fantastic (AppDraw, A2DP, Apps2SD, Automount USB etc)
